version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  groups:
    github-actions:
      patterns:
        - "*"  # Group all Actions updates into a single larger pull request
  schedule:
    interval: weekly
  cooldown:  # https://nesbitt.io/2026/03/04/package-managers-need-to-cool-down.html
    default-days: 7
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: standard
    versions:
    - 16.0.3
